version: '3'
services:
 mongodb:
   image: mongo
   ports:
     - "27017:27017"
   container_name: mongo-container
   network_mode: host
 muzixapp:
   image: muzixapp
   build: muzix/
   restart: always
   container_name: muzixapp-container
   network_mode: host
   ports:
     - "8080:8080"
   expose:
    - 8080
